apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gh-action-listener-ingress
  namespace: gh-action-listener
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - actions.pedanticorderliness.com
      secretName: gh-action-listener-tls
  rules:
    - host: actions.pedanticorderliness.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gh-action-listener-service
                port:
                  number: 80
